name: pico_sulteng_flutter
packages:
  - packages/*
  - features/*
  - shared/*
  - core/*
  - .

command:
  version:
    branch: master

scripts:
  generate-env:
    run: melos exec --depends-on="envied_generator" -- "dart run build_runner build -d"
  generate-locale:
    run: melos exec --depends-on="slang" -- "dart run slang"
    description: "Generate translation from arb."
  build:
    run: melos exec --depends-on="build_runner" -- "dart run build_runner build -d"
    description: "Run build runner in all packages that depend on it."
  format:
    run: melos exec -- "dart format . --fix && dart fix --apply"
    description: "Run dart format and dart fix for all packages"
  get:
    run: melos exec --depends-on="flutter" -- "flutter pub get"
    description: "Run `flutter pub get` in every packages."
  upgrade:
    run: melos exec --depends-on="flutter" -- "flutter pub upgrade"
    description: "Run `flutter pub upgrade` in every packages."
