name: pico_sulteng_flutter
version: 6.0.6+12
publish_to: none
description: Pusat Informasi Covid-19 Sulawesi Tengah
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_config: 2.0.0
  flutter_launcher_icons: 0.9.1
  flutter_native_splash: 1.2.1
  get: 4.3.6
  google_fonts: 2.1.0
  http: 0.13.3
  intl: 0.17.0
  lint: 1.5.3
  onesignal_flutter: 3.2.0
  shimmer: 2.0.0
  url_launcher: 6.0.9
  bubble_tab_indicator: 0.1.6
  carousel_slider: 4.0.0
  iconsax: 0.0.8
  pull_to_refresh: 2.0.0
  sleek_circular_slider: 2.0.1
  flutter_animation_progress_bar: 2.0.1
  lottie: 1.2.1
  line_icons: 2.0.1
  extended_image: 5.1.2
  flutter_spinkit: 5.1.0
  internet_connection_checker: 0.0.1+3
  eva_icons_flutter: 3.0.2
  flutter_inappwebview: 5.3.2
  animate_icons: 2.0.0
  infinite_scroll_pagination: 3.1.0
  flutter_app_name: 0.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/geojson/
    - assets/lottie/
  uses-material-design: true

flutter_native_splash: 
  image: assets/images/logo.png
  color: ffffff
  android_disable_fullscreen: true

flutter_icons: 
  image_path_ios: assets/images/logo.png
  image_path_android: assets/images/logo.png
  ios: true
  android: true

flutter_app_name:
  name: "PICO SulTeng"
