name: pico_sulteng_flutter
version: 7.0.0+13
publish_to: none
description: Pusat Informasi Covid-19 Sulawesi Tengah
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  config:
    path: shared/config
  core:
    path: core
  cupertino_icons: ^1.0.2
  dependencies:
    path: shared/dependencies
  flutter:
    sdk: flutter
  home:
    path: features/home
  i10n:
    path: shared/i10n
  pico_ui_kit:
    path: packages/pico_ui_kit
  statistic:
    path: features/statistic

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
  melos: ^3.4.0
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/geojson/

  uses-material-design: true
