name: pico_workspace
description: "A monorepo Flutter project with Melos for PICO SulTeng"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^4.0.0
