targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          include:
            - lib/src/router/wrapper/**.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          include:
            - lib/src/router/**.dart
      json_serializable:
        options:
          field_rename: snake
      freezed:freezed:
        generate_for:
          include:
            - lib/src/models/**.dart
