name: dependencies
description: "Dependencies of PICO Sulteng."
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  animate_icons: ^2.0.0
  auto_route: ^7.8.4
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  iconsax: ^0.0.8
  injectable: ^2.3.2
  intl: 0.18.1
  json_annotation: ^4.8.1
  line_icons: ^2.0.3
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
