name: dependencies
description: "Dependencies of PICO Sulteng."
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hydrated_bloc: ^9.1.3
  injectable: ^2.3.2
  intl: 0.18.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
