name: core
description: Core module of PICO SulTeng.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  config:
    path: ../../shared/config
  dependencies:
    path: ../../shared/dependencies
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_smart_retry: ^6.0.0
  flutter:
    sdk: flutter
  home:
    path: ../../features/home
  i10n:
    path: ../../shared/i10n
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  statistic:
    path: ../../features/statistic

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
