name: pico_ui_kit
description: "UI Kit for PICO SulTeng App."
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^4.2.1
  extended_image: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  i10n:
    path: ../../shared/i10n
  infinite_scroll_pagination: ^4.0.0
  lottie: ^2.7.0
  nil: ^1.1.1
  pull_to_refresh: ^2.0.0
  skeletonizer: ^0.8.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
  uses-material-design: true

flutter_gen:
  output: lib/src/assets/
  integrations:
    flutter_svg: true
    lottie: true
