name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: "**/*.md"
      modified_files_only: false

  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - name: 🤫 Set SSH Key
        env:
          ssh_key: ${{secrets.ssh_key}}
        if: env.ssh_key != null
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{secrets.ssh_key}}
      - name: 📦 Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          flutter pub global activate melos
          melos get
      - name: 📦 Prepare .env
        run: |
          cd shared/config
          cp .env.example .env.dev
          cp .env.example .env
          cp .env.example .env.stg
      - name: 📦 Run build_runner
        run: melos build
      - name: ✨ Fix Formatting
        run: melos format
      - name: ✨ Check Formatting
        run: melos format-check
      - name: 🕵️ Analyze
        run: melos analyze
      - name: 🧪 Run Tests
        run: melos test
